language: r
cache: packages
r_github_packages:
- yonicd/covrpage
- r-lib/pkgdown
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
after_failure:
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_KEY"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: WVdSXCZSwzQLLVZzvReRxxXfsBqAwJVu6nqCNYiFgpF1vFIjWLSLpPmQ9GJvPi2qfK7JhYVSgumD1WZvlicLJYZE8YDi92+xYzH0uL6Q4t1UaAjIfmLr3Vl6NvljraBVH3si40F8wwklaXifESCN6NuBEkPGNa6riMyP55g/9RLuaQPRIkvbXnhm+4QK1egvhuT2W4gRMq3oqzvE7IlmFOBHBLtDcSAI8OTJthFEtJneyXUc7NKx6vRRKu/0QFpW4oSP3Dxo5wzHrB56Awql1n4SBmXGKxR/JswkMKHTK2848xlmWbkn2Bj/uq4jB6nXEX9S6DDeh2gisgDHOOkwXJx+N7+VPEg6MKnY7ALbPz6brXFIcIePouNV1uj9TJlfBlvmZxjqnNFIErCwP63k8iwrUSGfB5XejyEwm6t2ZlYlDM8omrmDYxo92OldP2h/oWa8iDFfj72Kb6lZclgotFgtaXK85L4N8L9Mwg0yadCa4m1GPA9OcZlIoempPLj4NYv/jwJAq7WW8PAQNYS/xh7RomjKKvJPZO0XUG93giNbNhiI7aRDcdzpq8ZhLT6/loXiAhs055v1lY3SfUcuDtmVCWdn1ufM+8NPLkJ1t8wXJuOkGydP5zJBok8zM7Ft7lnFiR1B1Kxyayy1z+ZCl19n1bO80OJQdvUc+x41C0E=
