language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
- bash .travis/push.sh
env:
  global:
    secure: ehC0lVEbjIWqfJz2uGFtdUxLCqBM1QwLMWFFesfhksx38PFI9Ae91NWdxIe6XNC9sfdOhTeC5w+Cy6xv0mJqiDtHUySpq7MmcIs4FJkuzAaEHzjH+4zBPAZaswl7HWQWqjfixYqmmjNCb6JNShn4EXONE7SiXaVZtt/tHB75cwiEul24YC7DwDVpZfVVQVazew37S0QG/hgrNEv0W4l6JgcQNG7UQWq0DLkY7Fnn8GJciSgrHGupuF05DeCbbvuRlZrB/uSdTsQWvMKx67d/76SSIIoVgw2fLV8Zv/Ofkm9s8/JmHYTFa3Z3WuNZ+65YB27we2EPPY2F7Auietwe3Asfa1L3Omu14mUDoouwwCZ7aMp8CigAZBy+HmYjP1tnA+re15s6vfOhXagwNoQCkQnJoSzR5VycYT0+FHQpmp45WGvn09fzPbGzhUrbswTbfp9zbUhI1bLlFFeu/EO0MEZQe4PmYoaDXDcXek0hxP6BtsStoqUe3MjXI3ZIaYXq3AoN189kzeLq0YU8b01C1qoxrisHzjEsBm9moHI/o4sswLaefxDmwsXR9iVstSGsOyZrmwwrAbWQAjCDio7Hf0XrLNH7gDr8jDNXhjHsfIFsws63y1obLdJXU/9X8VV/+YgpKLEi8ZYiUbcWC280BI9P9et3ZlNSZhUvtIPvYNc=
